/* The following code was generated by JFlex 1.6.0 */

package analizadorlexico;
import java_cup.runtime.Symbol;
import analizadorlexico.TypeCheck.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>src/analizadorlexico/Flex/Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\44\1\46\1\50\1\47\1\47\22\0\1\44\1\0\1\56"+
    "\4\0\1\45\1\23\1\24\1\31\1\27\1\25\1\30\1\0\1\32"+
    "\12\43\1\36\1\37\1\34\1\35\1\33\2\0\1\26\1\16\1\4"+
    "\1\6\1\5\1\13\1\17\1\22\1\41\1\40\1\53\1\12\1\40"+
    "\1\11\1\3\1\1\1\40\1\2\1\42\1\10\1\7\1\55\1\20"+
    "\1\51\1\54\1\40\1\0\1\57\2\0\1\21\1\0\1\26\1\16"+
    "\1\4\1\6\1\5\1\13\1\17\1\22\1\41\1\40\1\53\1\12"+
    "\1\40\1\11\1\3\1\1\1\40\1\2\1\42\1\10\1\7\1\55"+
    "\1\20\1\51\1\54\1\40\12\0\1\50\252\0\2\14\115\0\1\15"+
    "\u1ea8\0\1\50\1\50\u0100\0\1\52\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\12\2\1\1\2\2\1\3\1\4\1\5"+
    "\1\2\2\6\2\7\2\10\1\11\1\12\1\2\1\13"+
    "\1\14\1\1\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\14\2\1\23\10\2\1\0\1\24\1\25\2\2\1\0"+
    "\3\2\1\26\1\10\1\27\1\30\1\2\1\24\1\25"+
    "\1\0\1\31\4\2\1\32\1\33\2\2\1\0\1\34"+
    "\1\0\1\2\1\0\6\2\1\35\3\2\1\0\3\2"+
    "\1\0\1\2\1\0\2\2\1\32\1\2\1\36\1\2"+
    "\1\0\4\2\1\0\1\2\1\37\2\40\2\41\1\42"+
    "\1\43\1\2\1\44\1\45\2\2\2\0\2\2\1\0"+
    "\1\2\1\46\1\47\1\0\1\2\1\46\2\2\1\0"+
    "\4\2\1\0\1\2\1\0\3\2\1\50\1\42\1\0"+
    "\1\2\1\51\2\52\2\53\2\2\1\0\1\2\1\54"+
    "\1\0\2\55\1\0\1\2\2\56\1\0\1\2\1\0"+
    "\1\2\1\0\3\2\1\0\1\2\1\57\1\0\1\2"+
    "\1\0\1\2\1\0\1\2\1\50\1\2\1\60\1\0"+
    "\1\2\2\61\2\62\1\63\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[206];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0"+
    "\0\u0300\0\220\0\220\0\220\0\u0330\0\220\0\u0360\0\220"+
    "\0\u0390\0\u0390\0\u03c0\0\u03f0\0\220\0\u0420\0\u0450\0\220"+
    "\0\u0480\0\220\0\220\0\220\0\u04b0\0\220\0\220\0\u04e0"+
    "\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660"+
    "\0\u0690\0\u06c0\0\u06f0\0\u01b0\0\u0720\0\u0750\0\u0780\0\u07b0"+
    "\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\220\0\220\0\u08d0"+
    "\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0\0\220\0\220\0\220"+
    "\0\220\0\u09f0\0\u01b0\0\u01b0\0\u0a20\0\220\0\u0a50\0\u0a80"+
    "\0\u0ab0\0\u0ae0\0\220\0\u01b0\0\u0b10\0\u0b40\0\u0b70\0\u01b0"+
    "\0\u0ba0\0\u0bd0\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0"+
    "\0\u0d20\0\u01b0\0\u0d50\0\u0d80\0\u0db0\0\u0de0\0\u0e10\0\u0e40"+
    "\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30\0\u0f60\0\u01b0\0\u0f90"+
    "\0\220\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0"+
    "\0\u1110\0\220\0\u1140\0\u1170\0\220\0\u01b0\0\u01b0\0\u01b0"+
    "\0\u11a0\0\u01b0\0\u01b0\0\u11d0\0\u1200\0\u1230\0\u1260\0\u1290"+
    "\0\u12c0\0\u12f0\0\u1320\0\220\0\u01b0\0\u1350\0\u1380\0\u01b0"+
    "\0\u13b0\0\u13e0\0\u1410\0\u1440\0\u1470\0\u14a0\0\u14d0\0\u1500"+
    "\0\u1530\0\u1560\0\u1590\0\u15c0\0\u15f0\0\u01b0\0\220\0\u1620"+
    "\0\u1650\0\220\0\220\0\u01b0\0\220\0\u01b0\0\u1680\0\u16b0"+
    "\0\u16e0\0\u1710\0\u01b0\0\u1740\0\220\0\u01b0\0\u1770\0\u17a0"+
    "\0\220\0\u01b0\0\u17d0\0\u1800\0\u1830\0\u1860\0\u1890\0\u18c0"+
    "\0\u18f0\0\u1920\0\u1950\0\u1980\0\220\0\u19b0\0\u19e0\0\u1a10"+
    "\0\u1a40\0\u1a70\0\u1aa0\0\220\0\u1ad0\0\220\0\u1b00\0\u1b30"+
    "\0\220\0\u01b0\0\220\0\u01b0\0\u01b0\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[206];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\2\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\4\1\20\1\12\1\21"+
    "\1\4\1\12\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\2\32\1\33\1\34\1\35\1\12\1\36"+
    "\1\12\1\37\1\40\1\41\2\40\1\0\1\12\1\4"+
    "\3\12\1\42\1\4\50\43\1\0\5\43\1\44\1\45"+
    "\44\46\1\40\1\46\1\47\1\40\1\0\7\46\61\0"+
    "\1\12\1\50\11\12\2\0\5\12\3\0\1\51\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\4\12\1\52\6\12\2\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\1\12\1\53\4\12\1\54\1\55\3\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\2\12\1\56\10\12\2\0\5\12"+
    "\3\0\1\57\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\10\12\1\60\1\61\1\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\62\1\0\3\12\3\0\13\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\1\12\1\63\1\64\10\12\2\0\4\12"+
    "\1\65\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\3\0\4\12\1\66\1\12\1\67"+
    "\4\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\2\12\1\70"+
    "\10\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\2\12\1\71"+
    "\3\12\1\72\2\12\1\73\1\12\2\0\5\12\3\0"+
    "\1\74\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\13\0\1\75\1\0\1\76\1\0\1\77\24\0"+
    "\1\77\16\0\2\12\1\100\1\12\1\101\6\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\3\0\13\12\1\102\1\0\4\12"+
    "\1\103\3\0\1\12\1\0\1\12\7\0\1\12\1\104"+
    "\2\12\5\0\1\12\1\0\3\12\3\0\10\12\1\105"+
    "\2\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\32\0\1\106\64\0"+
    "\1\107\55\0\1\110\61\0\1\111\23\0\10\12\1\112"+
    "\1\12\1\113\1\0\1\77\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\2\12\1\114\1\12\5\0\1\12\1\0"+
    "\3\12\45\0\1\37\14\0\46\115\3\0\7\115\56\0"+
    "\1\116\2\0\2\12\1\117\10\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\3\12\1\120\7\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\7\12\1\121\3\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\2\12\1\122\3\0\13\12\2\0\5\12\3\0\1\12"+
    "\1\0\1\12\6\0\1\123\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\7\12\1\124\3\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\13\12\2\0\4\12\1\125\3\0\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\3\12"+
    "\3\0\10\12\1\126\2\12\2\0\5\12\3\0\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\3\12"+
    "\3\0\13\12\1\0\1\127\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\5\12\1\130\5\12\2\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\13\12\1\0\1\131\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\2\12\1\132\1\12\5\0\1\12\1\0\3\12"+
    "\3\0\13\12\1\133\1\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\1\12\1\134\2\12\5\0\1\12\1\0"+
    "\3\12\3\0\6\12\1\135\4\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\4\12\1\136\6\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\13\12\2\0\2\12\1\137\2\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\11\12\1\140\1\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\2\12\1\141\10\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\1\12\1\142\11\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\10\12\1\143\2\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\2\12\1\144\10\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\11\12\1\145\1\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\12\0\1\146\50\0\2\12\1\147\2\12\1\150"+
    "\5\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\13\12\2\0"+
    "\1\12\1\151\3\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\12\0\1\152\50\0"+
    "\4\12\1\153\6\12\1\154\1\0\5\12\3\0\1\12"+
    "\1\0\1\12\7\0\1\12\1\155\2\12\5\0\1\12"+
    "\1\0\3\12\3\0\7\12\1\156\3\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\5\12\1\157\5\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\7\12\1\160\3\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\47\0\1\161\13\0\3\12\1\162\7\12"+
    "\2\0\5\12\3\0\1\12\1\0\1\12\7\0\4\12"+
    "\5\0\1\12\1\0\3\12\3\0\13\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\163\1\164\2\12\3\0\6\12\1\165\4\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\3\0\4\12\1\166\6\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\3\0\4\12\1\167\6\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\3\0\13\12\1\0\1\170\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\2\12\1\171\1\12"+
    "\5\0\1\12\1\0\3\12\7\0\1\172\57\0\1\173"+
    "\53\0\4\12\1\174\6\12\2\0\5\12\3\0\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\3\12"+
    "\12\0\1\175\50\0\7\12\1\176\3\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\4\12\1\177\6\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\10\12\1\200\2\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\13\12\2\0\3\12\1\201\1\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\11\12\1\202\1\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\1\203\12\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\3\12\1\204\7\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\13\12\2\0\5\12\3\0\1\205\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\13\12\1\0\1\206\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\2\12\1\135\1\12\5\0\1\12\1\0\3\12"+
    "\7\0\1\207\53\0\11\12\1\210\1\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\3\0\13\12\2\0\5\12\3\0\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\1\12"+
    "\1\211\1\12\3\0\13\12\1\212\1\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\1\12\1\213\2\12\5\0"+
    "\1\12\1\0\3\12\24\0\1\214\36\0\10\12\1\215"+
    "\2\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\14\0\1\216\46\0"+
    "\11\12\1\217\1\12\2\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\13\12\2\0\4\12\1\220\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\4\12"+
    "\1\221\6\12\2\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\4\12"+
    "\1\222\6\12\2\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\30\0\1\223"+
    "\32\0\13\12\2\0\5\12\3\0\1\224\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\1\12"+
    "\1\225\11\12\2\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\1\12"+
    "\1\226\11\12\2\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\1\12"+
    "\1\227\11\12\2\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\12\0\1\230"+
    "\50\0\7\12\1\231\3\12\2\0\5\12\3\0\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\3\12"+
    "\16\0\1\232\24\0\1\232\17\0\13\12\1\232\1\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\1\12\1\233"+
    "\2\12\5\0\1\12\1\0\3\12\3\0\11\12\1\234"+
    "\1\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\7\12\1\235"+
    "\3\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\7\12\1\236"+
    "\3\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\7\0\1\237\71\0"+
    "\1\240\41\0\4\12\1\241\6\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\13\12\2\0\5\12\2\0\1\242\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\3\12"+
    "\13\0\1\243\47\0\10\12\1\244\2\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\7\0\1\245\53\0\4\12\1\246\6\12"+
    "\2\0\5\12\3\0\1\12\1\0\1\12\7\0\4\12"+
    "\5\0\1\12\1\0\3\12\3\0\13\12\2\0\1\12"+
    "\1\247\3\12\3\0\1\12\1\0\1\12\7\0\4\12"+
    "\5\0\1\12\1\0\3\12\3\0\5\12\1\250\5\12"+
    "\2\0\5\12\3\0\1\12\1\0\1\12\7\0\4\12"+
    "\5\0\1\12\1\0\3\12\21\0\1\251\41\0\13\12"+
    "\2\0\1\12\1\252\3\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\10\12"+
    "\1\253\2\12\2\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\3\0\13\12"+
    "\1\0\1\254\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\13\12\1\0"+
    "\1\255\5\12\3\0\1\12\1\0\1\12\7\0\2\12"+
    "\1\256\1\12\5\0\1\12\1\0\3\12\30\0\1\257"+
    "\32\0\13\12\2\0\5\12\3\0\1\260\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\15\0\1\261"+
    "\45\0\12\12\1\262\2\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\3\0"+
    "\13\12\1\263\1\0\5\12\3\0\1\12\1\0\1\12"+
    "\7\0\1\12\1\264\2\12\5\0\1\12\1\0\3\12"+
    "\3\0\13\12\1\265\1\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\1\12\1\266\2\12\5\0\1\12\1\0"+
    "\3\12\7\0\1\267\53\0\13\12\2\0\5\12\3\0"+
    "\1\270\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\4\12\1\271\6\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\3\0\6\12\1\272\4\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\7\0\1\273\53\0\4\12\1\274\6\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\7\0\1\275\63\0\1\276\47\0"+
    "\10\12\1\277\2\12\2\0\5\12\3\0\1\12\1\0"+
    "\1\12\7\0\4\12\5\0\1\12\1\0\3\12\13\0"+
    "\1\300\47\0\10\12\1\301\2\12\2\0\5\12\3\0"+
    "\1\12\1\0\1\12\7\0\4\12\5\0\1\12\1\0"+
    "\3\12\5\0\1\302\55\0\2\12\1\303\10\12\2\0"+
    "\5\12\3\0\1\12\1\0\1\12\7\0\4\12\5\0"+
    "\1\12\1\0\3\12\4\0\1\304\56\0\10\12\1\236"+
    "\2\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\1\12\1\236"+
    "\11\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\3\0\1\12\1\305"+
    "\11\12\2\0\5\12\3\0\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\27\0\1\306\33\0"+
    "\13\12\2\0\5\12\2\0\1\306\1\12\1\0\1\12"+
    "\7\0\4\12\5\0\1\12\1\0\3\12\12\0\1\307"+
    "\50\0\7\12\1\310\3\12\2\0\5\12\3\0\1\12"+
    "\1\0\1\12\7\0\4\12\5\0\1\12\1\0\3\12"+
    "\7\0\1\311\53\0\4\12\1\312\6\12\2\0\5\12"+
    "\3\0\1\12\1\0\1\12\7\0\4\12\5\0\1\12"+
    "\1\0\3\12\13\0\1\313\47\0\10\12\1\314\2\12"+
    "\2\0\5\12\3\0\1\12\1\0\1\12\7\0\4\12"+
    "\5\0\1\12\1\0\3\12\3\0\4\12\1\315\6\12"+
    "\2\0\5\12\3\0\1\12\1\0\1\12\7\0\4\12"+
    "\5\0\1\12\1\0\3\12\27\0\1\316\33\0\13\12"+
    "\2\0\5\12\2\0\1\316\1\12\1\0\1\12\7\0"+
    "\4\12\5\0\1\12\1\0\3\12\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7008];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\15\1\3\11\1\1\1\11\1\1\1\11"+
    "\4\1\1\11\2\1\1\11\1\1\3\11\1\1\2\11"+
    "\25\1\1\0\2\11\2\1\1\0\3\1\4\11\3\1"+
    "\1\0\1\11\4\1\1\11\3\1\1\0\1\1\1\0"+
    "\1\1\1\0\12\1\1\0\3\1\1\0\1\1\1\0"+
    "\4\1\1\11\1\1\1\0\4\1\1\0\1\1\1\11"+
    "\2\1\1\11\10\1\2\0\2\1\1\0\1\1\1\11"+
    "\1\1\1\0\4\1\1\0\4\1\1\0\1\1\1\0"+
    "\4\1\1\11\1\0\1\1\2\11\1\1\1\11\3\1"+
    "\1\0\2\1\1\0\1\11\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\3\1\1\0"+
    "\1\1\1\11\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1\1\11\1\0\1\1\1\11\1\1\1\11"+
    "\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[206];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
     StringBuffer string = new StringBuffer();

     private Symbol symbol(int type) {
       return new Symbol(type, yyline, yycolumn);
      }
      private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
      }
      private void lexic_error(){
        System.err.print("Lexic Error:");
        System.err.print(" line:" + yyline);
        System.err.print(" column:" + yycolumn);
        System.err.println();
        System.err.print("Unknown Symbol: " + yytext());
        System.err.println();
        System.err.println();
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 224) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { lexic_error();
          }
        case 53: break;
        case 2: 
          { return symbol(sym.ID,yytext());
          }
        case 54: break;
        case 3: 
          { return symbol(sym.OPEN_PARENTHESIS);
          }
        case 55: break;
        case 4: 
          { return symbol(sym.CLOSE_PARENTHESIS);
          }
        case 56: break;
        case 5: 
          { return symbol(sym.COMMA);
          }
        case 57: break;
        case 6: 
          { return symbol(sym.SUM_OPERATOR,yytext());
          }
        case 58: break;
        case 7: 
          { return symbol(sym.MULT_OPERATOR,yytext());
          }
        case 59: break;
        case 8: 
          { return symbol(sym.RELATION_OPERATOR,yytext());
          }
        case 60: break;
        case 9: 
          { return symbol(sym.DECLARATION);
          }
        case 61: break;
        case 10: 
          { return symbol(sym.END_INSTRUCTION);
          }
        case 62: break;
        case 11: 
          { return symbol(sym.LITERAL_INT,yytext());
          }
        case 63: break;
        case 12: 
          { /* ignore */
          }
        case 64: break;
        case 13: 
          { string.setLength(0); yybegin(STRING);
          }
        case 65: break;
        case 14: 
          { string.append(yytext());
          }
        case 66: break;
        case 15: 
          { yybegin(YYINITIAL); return symbol(sym.LITERAL_STRING,string.toString());
          }
        case 67: break;
        case 16: 
          { string.append('\\');
          }
        case 68: break;
        case 17: 
          { /* Ignore */
          }
        case 69: break;
        case 18: 
          { yybegin(YYINITIAL);
          }
        case 70: break;
        case 19: 
          { return symbol(sym.TO);
          }
        case 71: break;
        case 20: 
          { return symbol(sym.IF);
          }
        case 72: break;
        case 21: 
          { return symbol(sym.IS);
          }
        case 73: break;
        case 22: 
          { yybegin(COMMENT);
          }
        case 74: break;
        case 23: 
          { return symbol(sym.CASEASIG);
          }
        case 75: break;
        case 24: 
          { return symbol(sym.ASIGNATION);
          }
        case 76: break;
        case 25: 
          { string.append('\"');
          }
        case 77: break;
        case 26: 
          { return symbol(sym.CONDITION_ELEMENT,yytext());
          }
        case 78: break;
        case 27: 
          { return symbol(sym.OUT);
          }
        case 79: break;
        case 28: 
          { return symbol(sym.END);
          }
        case 80: break;
        case 29: 
          { return symbol(sym.FOR);
          }
        case 81: break;
        case 30: 
          { return symbol(sym.LITERAL_CHAR,yytext());
          }
        case 82: break;
        case 31: 
          { return symbol(sym.CASE);
          }
        case 83: break;
        case 32: 
          { return symbol(sym.ELSE);
          }
        case 84: break;
        case 33: 
          { return symbol(sym.EXIT);
          }
        case 85: break;
        case 34: 
          { return symbol(sym.LITERAL_BOOLEAN,yytext());
          }
        case 86: break;
        case 35: 
          { return symbol(sym.THEN);
          }
        case 87: break;
        case 36: 
          { return symbol(sym.NULL);
          }
        case 88: break;
        case 37: 
          { return symbol(sym.LOOP);
          }
        case 89: break;
        case 38: 
          { return symbol(sym.WITH);
          }
        case 90: break;
        case 39: 
          { return symbol(sym.WHEN);
          }
        case 91: break;
        case 40: 
          { String text = yytext().toUpperCase();
                          Type retType = null;
                          if (text.equals("INTEGER")){
                            retType = new IntType();
                          }else if (text.equals("FLOAT")){
                            retType = new FloatType();
                          }else if (text.equals("BOOLEAN")){
                            retType = new BooleanType();
                          }
                          return symbol(sym.TYPE,retType);
          }
        case 92: break;
        case 41: 
          { return symbol(sym.BODY);
          }
        case 93: break;
        case 42: 
          { return symbol(sym.BEGIN);
          }
        case 94: break;
        case 43: 
          { return symbol(sym.WHILE);
          }
        case 95: break;
        case 44: 
          { return symbol(sym.RETURN);
          }
        case 96: break;
        case 45: 
          { return symbol(sym.OTHERS);
          }
        case 97: break;
        case 46: 
          { return symbol(sym.ELSEIF);
          }
        case 98: break;
        case 47: 
          { return symbol(sym.REVERSE);
          }
        case 99: break;
        case 48: 
          { return symbol(sym.PACKAGE);
          }
        case 100: break;
        case 49: 
          { return symbol(sym.NEW_LINE);
          }
        case 101: break;
        case 50: 
          { return symbol(sym.FUNCTION);
          }
        case 102: break;
        case 51: 
          { return symbol(sym.PROCEDURE);
          }
        case 103: break;
        case 52: 
          { return symbol(sym.CONSTANT);
          }
        case 104: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
