/* The following code was generated by JFlex 1.6.0 */

package analizadorlexico;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>src/analizadorlexico/Flex/Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\53\1\55\1\57\1\56\1\56\22\0\1\53\1\0\1\65"+
    "\1\43\3\0\1\54\1\23\1\24\1\31\1\27\1\25\1\30\1\0"+
    "\1\32\12\52\1\36\1\37\1\34\1\35\1\33\2\0\1\51\1\50"+
    "\1\44\1\46\1\45\1\47\1\17\1\22\1\41\1\40\1\62\1\12"+
    "\1\40\1\11\1\3\1\1\1\40\1\2\1\42\1\10\1\7\1\64"+
    "\1\20\1\60\1\63\1\40\1\0\1\66\2\0\1\21\1\0\1\26"+
    "\1\16\1\4\1\6\1\5\1\13\1\17\1\22\1\41\1\40\1\62"+
    "\1\12\1\40\1\11\1\3\1\1\1\40\1\2\1\42\1\10\1\7"+
    "\1\64\1\20\1\60\1\63\1\40\12\0\1\57\252\0\2\14\115\0"+
    "\1\15\u1ea8\0\1\57\1\57\u0100\0\1\61\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\12\1\1\0\2\1\1\2\1\3\1\4\1\1"+
    "\2\5\2\6\2\7\1\10\1\11\1\1\1\12\1\13"+
    "\1\0\1\14\1\15\1\16\1\17\1\20\1\21\14\1"+
    "\1\22\10\1\1\0\1\23\1\24\2\1\1\0\3\1"+
    "\1\25\1\7\1\26\1\27\1\1\1\23\1\24\2\0"+
    "\1\30\4\1\1\31\1\32\2\1\1\0\1\33\1\0"+
    "\1\1\1\0\6\1\1\34\3\1\1\0\3\1\1\0"+
    "\1\1\1\0\2\1\1\31\1\1\1\0\1\35\1\1"+
    "\1\0\4\1\1\0\1\1\1\36\2\37\2\40\1\41"+
    "\1\42\1\1\1\43\1\44\2\1\2\0\2\1\1\0"+
    "\1\1\1\45\1\46\1\0\1\1\1\45\1\1\1\12"+
    "\1\1\1\0\4\1\1\0\1\1\1\0\3\1\1\47"+
    "\1\41\1\0\1\1\1\50\2\51\2\52\2\1\1\0"+
    "\1\1\1\53\1\0\2\54\1\0\1\1\2\55\1\0"+
    "\1\1\1\0\1\1\1\0\3\1\1\0\1\1\1\56"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\47\1\1"+
    "\1\57\1\0\1\1\2\60\2\61\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339"+
    "\0\u0370\0\u0370\0\u0370\0\u03a7\0\u0370\0\u03de\0\u0370\0\u0415"+
    "\0\u0415\0\u044c\0\u0483\0\u0370\0\u04ba\0\u04f1\0\u0370\0\u0528"+
    "\0\u0370\0\u0370\0\u0370\0\u055f\0\u0370\0\u0370\0\u0596\0\u05cd"+
    "\0\u0604\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785"+
    "\0\u07bc\0\u07f3\0\u01b8\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906"+
    "\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0370\0\u0370\0\u0a19\0\u0a50"+
    "\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0370\0\u0370\0\u0370\0\u0370"+
    "\0\u0b63\0\u01b8\0\u01b8\0\u0b9a\0\u0bd1\0\u0370\0\u0c08\0\u0c3f"+
    "\0\u0c76\0\u0cad\0\u0370\0\u01b8\0\u0ce4\0\u0d1b\0\u0d52\0\u01b8"+
    "\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a"+
    "\0\u0f41\0\u01b8\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b"+
    "\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\u01b8\0\u120c"+
    "\0\u1243\0\u0370\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d"+
    "\0\u13c4\0\u13fb\0\u0370\0\u1432\0\u1469\0\u0370\0\u01b8\0\u01b8"+
    "\0\u01b8\0\u14a0\0\u01b8\0\u01b8\0\u14d7\0\u150e\0\u1545\0\u157c"+
    "\0\u15b3\0\u15ea\0\u1621\0\u1658\0\u0370\0\u01b8\0\u168f\0\u16c6"+
    "\0\u01b8\0\u16fd\0\u0370\0\u1734\0\u176b\0\u17a2\0\u17d9\0\u1810"+
    "\0\u1847\0\u187e\0\u18b5\0\u18ec\0\u1923\0\u195a\0\u1991\0\u01b8"+
    "\0\u0370\0\u19c8\0\u19ff\0\u0370\0\u0370\0\u01b8\0\u0370\0\u01b8"+
    "\0\u1a36\0\u1a6d\0\u1aa4\0\u1adb\0\u01b8\0\u1b12\0\u0370\0\u01b8"+
    "\0\u1b49\0\u1b80\0\u0370\0\u01b8\0\u1bb7\0\u1bee\0\u1c25\0\u1c5c"+
    "\0\u1c93\0\u1cca\0\u1d01\0\u1d38\0\u1d6f\0\u1da6\0\u0370\0\u1ddd"+
    "\0\u1e14\0\u1e4b\0\u1e82\0\u1eb9\0\u1ef0\0\u0370\0\u1f27\0\u0370"+
    "\0\u1f5e\0\u1f95\0\u0370\0\u01b8\0\u0370\0\u01b8\0\u01b8\0\u0370";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\4\1\5\1\6\1\7\1\10\2\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\0\1\17\1\11\1\20"+
    "\1\0\1\11\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\2\31\1\32\1\33\1\34\1\11\1\35"+
    "\1\11\1\0\1\7\1\10\1\11\1\15\1\17\1\24"+
    "\1\36\1\37\1\40\2\37\1\0\1\11\1\0\3\11"+
    "\1\41\1\0\57\42\1\0\5\42\1\43\1\44\53\45"+
    "\1\37\1\45\1\46\1\37\1\0\7\45\1\0\1\11"+
    "\1\47\11\11\2\0\5\11\3\0\1\50\1\0\1\11"+
    "\7\0\3\11\1\0\5\11\1\50\1\11\5\0\1\11"+
    "\1\0\3\11\3\0\4\11\1\51\6\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\1\11"+
    "\1\51\5\11\5\0\1\11\1\0\3\11\3\0\1\11"+
    "\1\52\4\11\1\53\1\54\3\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\3\0\2\11\1\55\10\11\2\0"+
    "\5\11\3\0\1\56\1\0\1\11\7\0\3\11\1\0"+
    "\5\11\1\56\1\11\5\0\1\11\1\0\3\11\3\0"+
    "\10\11\1\57\1\60\1\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\7\11\5\0\1\61"+
    "\1\0\3\11\3\0\13\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\3\0\1\11\1\62\1\63\10\11\2\0"+
    "\4\11\1\64\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\4\11"+
    "\1\65\1\11\1\66\4\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\1\11\1\65\5\11"+
    "\5\0\1\11\1\0\3\11\3\0\2\11\1\67\10\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\2\11"+
    "\1\70\3\11\1\71\2\11\1\72\1\11\2\0\5\11"+
    "\3\0\1\73\1\0\1\11\7\0\3\11\1\0\5\11"+
    "\1\73\1\11\5\0\1\11\1\0\3\11\13\0\1\74"+
    "\1\0\1\75\1\0\1\76\24\0\1\76\4\0\1\75"+
    "\20\0\2\11\1\77\1\11\1\100\6\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\1\11"+
    "\1\100\5\11\5\0\1\11\1\0\3\11\3\0\13\11"+
    "\1\101\1\0\4\11\1\102\3\0\1\11\1\0\1\11"+
    "\7\0\1\11\1\103\1\11\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\72\0\10\11\1\104\2\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\7\11"+
    "\5\0\1\11\1\0\3\11\32\0\1\105\73\0\1\106"+
    "\64\0\1\107\70\0\1\110\32\0\10\11\1\111\1\11"+
    "\1\112\1\0\1\76\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\2\11\1\113\1\0\3\11\1\112\3\11\5\0"+
    "\1\11\1\0\3\11\45\0\1\114\6\0\1\36\14\0"+
    "\55\115\3\0\7\115\65\0\1\116\2\0\2\11\1\117"+
    "\10\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\3\11\1\120\7\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\1\120\6\11\5\0\1\11"+
    "\1\0\3\11\3\0\7\11\1\121\3\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\7\11"+
    "\5\0\1\11\1\0\2\11\1\122\3\0\13\11\2\0"+
    "\5\11\3\0\1\11\1\0\1\11\6\0\1\123\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\7\11"+
    "\1\124\3\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\7\11\5\0\1\11\1\0\3\11"+
    "\3\0\13\11\2\0\4\11\1\125\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\3\0\10\11\1\126\2\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\3\0\13\11\1\0\1\127\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\7\11"+
    "\5\0\1\11\1\0\3\11\3\0\5\11\1\130\5\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\2\11\1\130\4\11\5\0\1\11\1\0\3\11"+
    "\3\0\13\11\1\0\1\131\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\2\11\1\132\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\3\0\13\11\1\133\1\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\1\11\1\134\1\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\3\0\6\11\1\135"+
    "\4\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\4\11\1\136\6\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\1\11\1\136\5\11\5\0"+
    "\1\11\1\0\3\11\3\0\13\11\2\0\2\11\1\137"+
    "\2\11\3\0\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\3\0\11\11\1\140"+
    "\1\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\2\11\1\141\10\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\3\0\1\11\1\142\11\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\3\0\10\11\1\143\2\11\2\0"+
    "\5\11\3\0\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\3\0\2\11\1\144"+
    "\10\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\11\11\1\145\1\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\12\0\1\146\57\0\2\11\1\147\2\11\1\150"+
    "\5\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\2\11\1\150\4\11\5\0\1\11\1\0"+
    "\3\11\3\0\13\11\2\0\1\11\1\151\3\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\12\0\1\152\57\0\4\11\1\153"+
    "\6\11\1\154\1\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\1\11\1\155\1\11\1\0\1\11\1\153\5\11"+
    "\5\0\1\11\1\0\3\11\3\0\7\11\1\156\3\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\5\11"+
    "\1\157\5\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\2\11\1\157\4\11\5\0\1\11"+
    "\1\0\3\11\3\0\7\11\1\160\3\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\7\11"+
    "\5\0\1\11\1\0\3\11\46\0\7\161\70\0\1\162"+
    "\13\0\3\11\1\163\7\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\1\163\6\11\5\0"+
    "\1\11\1\0\3\11\3\0\13\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\164\1\165\2\11\3\0\6\11\1\166\4\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\4\11"+
    "\1\167\6\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\1\11\1\167\5\11\5\0\1\11"+
    "\1\0\3\11\3\0\4\11\1\170\6\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\1\11"+
    "\1\170\5\11\5\0\1\11\1\0\3\11\3\0\13\11"+
    "\1\0\1\171\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\2\11\1\172\1\0\7\11\5\0\1\11\1\0\3\11"+
    "\7\0\1\173\37\0\1\173\26\0\1\174\37\0\1\174"+
    "\22\0\4\11\1\175\6\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\1\11\1\175\5\11"+
    "\5\0\1\11\1\0\3\11\12\0\1\176\57\0\7\11"+
    "\1\177\3\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\7\11\5\0\1\11\1\0\3\11"+
    "\3\0\4\11\1\200\6\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\1\11\1\200\5\11"+
    "\5\0\1\11\1\0\3\11\3\0\10\11\1\201\2\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\13\11"+
    "\2\0\3\11\1\202\1\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\7\11\5\0\1\11\1\0\3\11"+
    "\3\0\11\11\1\203\1\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\3\0\1\204\12\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\3\0\3\11\1\205\7\11\2\0"+
    "\5\11\3\0\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\1\205\6\11\5\0\1\11\1\0\3\11\3\0\13\11"+
    "\2\0\5\11\3\0\1\206\1\0\1\11\7\0\3\11"+
    "\1\0\5\11\1\206\1\11\5\0\1\11\1\0\3\11"+
    "\3\0\13\11\1\0\1\207\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\2\11\1\135\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\7\0\1\210\37\0\1\210\22\0\11\11"+
    "\1\211\1\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\7\11\5\0\1\11\1\0\3\11"+
    "\3\0\13\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\7\11\5\0\1\11\1\0\1\11"+
    "\1\212\1\11\3\0\13\11\1\213\1\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\1\11\1\214\1\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\24\0\1\215\45\0"+
    "\10\11\1\216\2\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\14\0\1\217\55\0\11\11\1\220\1\11\2\0"+
    "\5\11\3\0\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\3\0\13\11\2\0"+
    "\4\11\1\221\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\4\11"+
    "\1\222\6\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\1\11\1\222\5\11\5\0\1\11"+
    "\1\0\3\11\45\0\1\223\7\161\15\0\4\11\1\224"+
    "\6\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\1\11\1\224\5\11\5\0\1\11\1\0"+
    "\3\11\30\0\1\225\22\0\1\225\16\0\13\11\2\0"+
    "\5\11\3\0\1\226\1\0\1\11\7\0\3\11\1\0"+
    "\5\11\1\226\1\11\5\0\1\11\1\0\3\11\3\0"+
    "\1\11\1\227\11\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\3\0\1\11\1\230\11\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\3\0\1\11\1\231\11\11\2\0"+
    "\5\11\3\0\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\12\0\1\232\57\0"+
    "\7\11\1\233\3\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\16\0\1\234\24\0\1\234\26\0\13\11\1\234"+
    "\1\0\5\11\3\0\1\11\1\0\1\11\7\0\1\11"+
    "\1\235\1\11\1\0\7\11\5\0\1\11\1\0\3\11"+
    "\3\0\11\11\1\236\1\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\3\0\7\11\1\237\3\11\2\0\5\11"+
    "\3\0\1\11\1\0\1\11\7\0\3\11\1\0\7\11"+
    "\5\0\1\11\1\0\3\11\3\0\7\11\1\240\3\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\7\0\1\241"+
    "\37\0\1\241\40\0\1\242\50\0\4\11\1\243\6\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\1\11\1\243\5\11\5\0\1\11\1\0\3\11"+
    "\3\0\13\11\2\0\5\11\2\0\1\244\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\13\0\1\245\56\0\10\11\1\246\2\11\2\0"+
    "\5\11\3\0\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\7\0\1\247\37\0"+
    "\1\247\22\0\4\11\1\250\6\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\1\11\1\250"+
    "\5\11\5\0\1\11\1\0\3\11\3\0\13\11\2\0"+
    "\1\11\1\251\3\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\5\11\1\252\5\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\2\11\1\252\4\11\5\0"+
    "\1\11\1\0\3\11\21\0\1\253\50\0\13\11\2\0"+
    "\1\11\1\254\3\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\10\11\1\255\2\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\3\0\13\11\1\0\1\256\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\3\0\13\11\1\0\1\257\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\2\11\1\260\1\0\7\11"+
    "\5\0\1\11\1\0\3\11\30\0\1\261\22\0\1\261"+
    "\16\0\13\11\2\0\5\11\3\0\1\262\1\0\1\11"+
    "\7\0\3\11\1\0\5\11\1\262\1\11\5\0\1\11"+
    "\1\0\3\11\15\0\1\263\33\0\1\263\20\0\12\11"+
    "\1\264\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\3\11\1\264\3\11\5\0\1\11\1\0"+
    "\3\11\3\0\13\11\1\265\1\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\1\11\1\266\1\11\1\0\7\11"+
    "\5\0\1\11\1\0\3\11\3\0\13\11\1\267\1\0"+
    "\5\11\3\0\1\11\1\0\1\11\7\0\1\11\1\270"+
    "\1\11\1\0\7\11\5\0\1\11\1\0\3\11\7\0"+
    "\1\271\37\0\1\271\22\0\13\11\2\0\5\11\3\0"+
    "\1\272\1\0\1\11\7\0\3\11\1\0\5\11\1\272"+
    "\1\11\5\0\1\11\1\0\3\11\3\0\4\11\1\273"+
    "\6\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\1\11\1\273\5\11\5\0\1\11\1\0"+
    "\3\11\3\0\6\11\1\274\4\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\7\0\1\275\37\0\1\275\22\0"+
    "\4\11\1\276\6\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\1\11\1\276\5\11\5\0"+
    "\1\11\1\0\3\11\7\0\1\277\37\0\1\277\32\0"+
    "\1\300\56\0\10\11\1\301\2\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\13\0\1\302\56\0\10\11\1\303"+
    "\2\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\5\0"+
    "\1\304\64\0\2\11\1\305\10\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\4\0\1\306\65\0\10\11\1\240"+
    "\2\11\2\0\5\11\3\0\1\11\1\0\1\11\7\0"+
    "\3\11\1\0\7\11\5\0\1\11\1\0\3\11\3\0"+
    "\1\11\1\240\11\11\2\0\5\11\3\0\1\11\1\0"+
    "\1\11\7\0\3\11\1\0\7\11\5\0\1\11\1\0"+
    "\3\11\3\0\1\11\1\307\11\11\2\0\5\11\3\0"+
    "\1\11\1\0\1\11\7\0\3\11\1\0\7\11\5\0"+
    "\1\11\1\0\3\11\27\0\1\310\42\0\13\11\2\0"+
    "\5\11\2\0\1\310\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\12\0\1\311"+
    "\57\0\7\11\1\312\3\11\2\0\5\11\3\0\1\11"+
    "\1\0\1\11\7\0\3\11\1\0\7\11\5\0\1\11"+
    "\1\0\3\11\7\0\1\313\37\0\1\313\22\0\4\11"+
    "\1\314\6\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\1\11\1\314\5\11\5\0\1\11"+
    "\1\0\3\11\13\0\1\315\56\0\10\11\1\316\2\11"+
    "\2\0\5\11\3\0\1\11\1\0\1\11\7\0\3\11"+
    "\1\0\7\11\5\0\1\11\1\0\3\11\3\0\4\11"+
    "\1\317\6\11\2\0\5\11\3\0\1\11\1\0\1\11"+
    "\7\0\3\11\1\0\1\11\1\317\5\11\5\0\1\11"+
    "\1\0\3\11\27\0\1\320\42\0\13\11\2\0\5\11"+
    "\2\0\1\320\1\11\1\0\1\11\7\0\3\11\1\0"+
    "\7\11\5\0\1\11\1\0\3\11\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8140];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\12\1\1\0\2\1\3\11\1\1\1\11\1\1"+
    "\1\11\4\1\1\11\2\1\1\11\1\0\3\11\1\1"+
    "\2\11\25\1\1\0\2\11\2\1\1\0\3\1\4\11"+
    "\3\1\2\0\1\11\4\1\1\11\3\1\1\0\1\1"+
    "\1\0\1\1\1\0\12\1\1\0\3\1\1\0\1\1"+
    "\1\0\4\1\1\0\1\11\1\1\1\0\4\1\1\0"+
    "\1\1\1\11\2\1\1\11\10\1\2\0\2\1\1\0"+
    "\1\1\1\11\1\1\1\0\3\1\1\11\1\1\1\0"+
    "\4\1\1\0\1\1\1\0\4\1\1\11\1\0\1\1"+
    "\2\11\1\1\1\11\3\1\1\0\2\1\1\0\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\1\0\1\1\1\11\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\11\1\1\1\11\1\0"+
    "\1\1\1\11\1\1\1\11\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
     StringBuffer string = new StringBuffer();

     private Symbol symbol(int type) {
       return new Symbol(type, yyline, yycolumn);
      }
      private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 226) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return symbol(sym.ID,yytext());
          }
        case 52: break;
        case 2: 
          { return symbol(sym.OPEN_PARENTHESIS);
          }
        case 53: break;
        case 3: 
          { return symbol(sym.CLOSE_PARENTHESIS);
          }
        case 54: break;
        case 4: 
          { return symbol(sym.COMMA);
          }
        case 55: break;
        case 5: 
          { return symbol(sym.SUM_OPERATOR,yytext());
          }
        case 56: break;
        case 6: 
          { return symbol(sym.MULT_OPERATOR,yytext());
          }
        case 57: break;
        case 7: 
          { return symbol(sym.RELATION_OPERATOR,yytext());
          }
        case 58: break;
        case 8: 
          { return symbol(sym.DECLARATION);
          }
        case 59: break;
        case 9: 
          { return symbol(sym.END_INSTRUCTION);
          }
        case 60: break;
        case 10: 
          { return symbol(sym.LITERAL_INT,yytext());
          }
        case 61: break;
        case 11: 
          { /* ignore */
          }
        case 62: break;
        case 12: 
          { string.setLength(0); yybegin(STRING);
          }
        case 63: break;
        case 13: 
          { string.append(yytext());
          }
        case 64: break;
        case 14: 
          { yybegin(YYINITIAL); return symbol(sym.LITERAL_STRING,string.toString());
          }
        case 65: break;
        case 15: 
          { string.append('\\');
          }
        case 66: break;
        case 16: 
          { /* Ignore */
          }
        case 67: break;
        case 17: 
          { yybegin(YYINITIAL);
          }
        case 68: break;
        case 18: 
          { return symbol(sym.TO);
          }
        case 69: break;
        case 19: 
          { return symbol(sym.IF);
          }
        case 70: break;
        case 20: 
          { return symbol(sym.IS);
          }
        case 71: break;
        case 21: 
          { yybegin(COMMENT);
          }
        case 72: break;
        case 22: 
          { return symbol(sym.CASEASIG);
          }
        case 73: break;
        case 23: 
          { return symbol(sym.ASIGNATION);
          }
        case 74: break;
        case 24: 
          { string.append('\"');
          }
        case 75: break;
        case 25: 
          { return symbol(sym.CONDITION_ELEMENT,yytext());
          }
        case 76: break;
        case 26: 
          { return symbol(sym.OUT);
          }
        case 77: break;
        case 27: 
          { return symbol(sym.END);
          }
        case 78: break;
        case 28: 
          { return symbol(sym.FOR);
          }
        case 79: break;
        case 29: 
          { return symbol(sym.LITERAL_CHAR,yytext());
          }
        case 80: break;
        case 30: 
          { return symbol(sym.CASE);
          }
        case 81: break;
        case 31: 
          { return symbol(sym.ELSE);
          }
        case 82: break;
        case 32: 
          { return symbol(sym.EXIT);
          }
        case 83: break;
        case 33: 
          { return symbol(sym.LITERAL_BOOLEAN,yytext());
          }
        case 84: break;
        case 34: 
          { return symbol(sym.THEN);
          }
        case 85: break;
        case 35: 
          { return symbol(sym.NULL);
          }
        case 86: break;
        case 36: 
          { return symbol(sym.LOOP);
          }
        case 87: break;
        case 37: 
          { return symbol(sym.WITH);
          }
        case 88: break;
        case 38: 
          { return symbol(sym.WHEN);
          }
        case 89: break;
        case 39: 
          { return symbol(sym.TYPE,yytext());
          }
        case 90: break;
        case 40: 
          { return symbol(sym.BODY);
          }
        case 91: break;
        case 41: 
          { return symbol(sym.BEGIN);
          }
        case 92: break;
        case 42: 
          { return symbol(sym.WHILE);
          }
        case 93: break;
        case 43: 
          { return symbol(sym.RETURN);
          }
        case 94: break;
        case 44: 
          { return symbol(sym.OTHERS);
          }
        case 95: break;
        case 45: 
          { return symbol(sym.ELSEIF);
          }
        case 96: break;
        case 46: 
          { return symbol(sym.REVERSE);
          }
        case 97: break;
        case 47: 
          { return symbol(sym.PACKAGE);
          }
        case 98: break;
        case 48: 
          { return symbol(sym.NEW_LINE);
          }
        case 99: break;
        case 49: 
          { return symbol(sym.FUNCTION);
          }
        case 100: break;
        case 50: 
          { return symbol(sym.PROCEDURE);
          }
        case 101: break;
        case 51: 
          { return symbol(sym.CONSTANT);
          }
        case 102: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
