
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 24 13:25:09 CDT 2016
//----------------------------------------------------

package analizadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 24;
  public static final int FUNCTION = 27;
  public static final int RELATION_OPERATOR = 42;
  public static final int WITH = 7;
  public static final int PUT = 38;
  public static final int END_INSTRUCTION = 10;
  public static final int SUM_OPERATOR = 40;
  public static final int CASE = 32;
  public static final int CONDITION_ELEMENT = 43;
  public static final int OUT = 18;
  public static final int FOR = 16;
  public static final int REVERSE = 34;
  public static final int IS = 3;
  public static final int ELSEIF = 14;
  public static final int TYPE = 44;
  public static final int IN = 17;
  public static final int COMMA = 25;
  public static final int LITERAL_BOOLEAN = 45;
  public static final int BEGIN = 4;
  public static final int LOOP = 19;
  public static final int EXIT = 23;
  public static final int IF = 12;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int error = 1;
  public static final int LITERAL_CHAR = 11;
  public static final int NULL = 31;
  public static final int CONSTANT = 26;
  public static final int ASIGNATION = 21;
  public static final int DECLARATION = 22;
  public static final int OPEN_PARENTHESIS = 8;
  public static final int LITERAL_INT = 46;
  public static final int ELSE = 13;
  public static final int OTHERS = 35;
  public static final int MULT_OPERATOR = 41;
  public static final int LITERAL_STRING = 39;
  public static final int TO = 36;
  public static final int PACKAGE = 28;
  public static final int NEW_LINE = 6;
  public static final int WHILE = 20;
  public static final int THEN = 15;
  public static final int BODY = 29;
  public static final int END = 5;
  public static final int CASEASIG = 33;
  public static final int CLOSE_PARENTHESIS = 9;
  public static final int PROCEDURE = 2;
}

