
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 13 13:40:51 CST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEN_PARENTHESIS = 9;
  public static final int PROCEDURE = 2;
  public static final int IS = 3;
  public static final int SUM_OPERATOR = 11;
  public static final int ELSE = 20;
  public static final int THEN = 22;
  public static final int WHILE = 26;
  public static final int IN = 24;
  public static final int LOOP = 25;
  public static final int END_INSTRUCTION = 17;
  public static final int END = 5;
  public static final int MULT_OPERATOR = 12;
  public static final int IF = 19;
  public static final int ID = 27;
  public static final int WITH = 8;
  public static final int PUT = 6;
  public static final int NEW_LINE = 7;
  public static final int BEGIN = 4;
  public static final int TYPE = 14;
  public static final int EOF = 0;
  public static final int ELSEIF = 21;
  public static final int LITERAL_BOOLEAN = 15;
  public static final int error = 1;
  public static final int LITERAL_CHAR = 18;
  public static final int LITERAL_INT = 16;
  public static final int FOR = 23;
  public static final int CLOSE_PARENTHESIS = 10;
  public static final int RELATION_OPERATOR = 13;
}

